# Generated by Django 5.1.1 on 2024-11-11 11:15

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='orginal_price',
            new_name='original_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='path/to/default/image.jpg', null=True, upload_to=shop.models.getFileName),
        ),
    ]
