# Generated by Django 5.1.1 on 2024-11-15 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_products_image_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='reated_at',
            new_name='created_at',
        ),
    ]
